### ISSUE TITLE
16bits for motor_inductance is too small for some small gimbal motors

### ISSUE THREAD

**Issue by DarrenLevine** [tinymovr/Tinymovr#156]
I'm using a small gimbal motor (T-Motor GB36-1) with tinymovr, and according to a LCR meter (assuming I'm measuring it correctly...) the motor has a high inductance of 158,300 microhenries. The tmx.set_motor_config interface only allows 16bit values for motor_inductance in microhenries, so it can't represent a large enough value for this specific motor. Jamming in the highest inductance I can and then manual tuning of the gains lets me get around this and control the motor in position-control mode, though it's perhaps more manual than would be ideal.

**Comment by yconst** [comment]
Thanks for this issue. Indeed this is a limitation, that came due to the limited size of the CAN frame. We're working on a large refactoring of the comms but it's early for that and it will take some time. In the meantime, we could refactor the endpoints to use two separate ones, one for instance for configuring R and L and one for pole pairs, flags and calibration current.
